name: techpulse
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.12  # Specify the Python version you want
  - accelerate=0.26.0=pyhd8ed1ab_0
  - onnxruntime=1.17.1=py312hade572d_0
  - torchaudio=2.4.1=py312_cpu
  - torchvision=0.19.1=py312_cpu
  - pip:
    - altair==5.4.1
    - accelerate==0.26.0
    - datasets==1.18.3
    - tqdm==4.65.0
    - streamlit==1.18.1
    - pandas==2.2.3
    - plotly==5.24.1
    - torch==2.4.1
    - transformers==4.44.2
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - requests==2.31.0
    - praw==7.7.1
    - python-dotenv==1.0.1
    - matplotlib==3.9.2
    - vaderSentiment==3.3.2
    - scikit-learn==1.5.0
    - numpy==1.26.4
    - huggingface-hub==0.25.2
    - bert-score==0.3.13
    - chromadb==0.5.13
    - nltk==3.9.1
    - wordcloud==1.9.3